<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('gbk');
E_D("DROP TABLE IF EXISTS `qb_label`;");
E_C("CREATE TABLE `qb_label` (
  `lid` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `ch` smallint(4) NOT NULL DEFAULT '0',
  `chtype` tinyint(2) NOT NULL DEFAULT '0',
  `tag` varchar(50) NOT NULL DEFAULT '',
  `type` varchar(30) NOT NULL DEFAULT '',
  `typesystem` tinyint(1) NOT NULL DEFAULT '0',
  `code` text NOT NULL,
  `divcode` text,
  `hide` tinyint(1) NOT NULL DEFAULT '0',
  `js_time` int(10) NOT NULL DEFAULT '0',
  `uid` mediumint(7) NOT NULL DEFAULT '0',
  `username` varchar(30) NOT NULL DEFAULT '',
  `posttime` int(10) NOT NULL DEFAULT '0',
  `pagetype` tinyint(3) NOT NULL DEFAULT '0',
  `module` mediumint(6) NOT NULL DEFAULT '0',
  `fid` mediumint(7) NOT NULL DEFAULT '0',
  `if_js` tinyint(1) NOT NULL DEFAULT '0',
  `style` varchar(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`lid`),
  KEY `ch` (`ch`,`pagetype`,`module`,`fid`,`chtype`),
  KEY `tag` (`tag`)
) ENGINE=MyISAM AUTO_INCREMENT=168 DEFAULT CHARSET=gbk");
E_D("replace into `qb_label` values('1','','0','99','searchhotword','code','0','<A href=\"#\">求购三房一顶</A> <A href=\"#\">出售毛坯房</A>','a:4:{s:9:\"html_edit\";N;s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','blue');");
E_D("replace into `qb_label` values('2','','0','0','abc_ads2','Info_fenlei_','1','a:30:{s:13:\"tplpart_1code\";s:112:\"<div style=\"line-height:180%;\">·<A HREF=\"\$url\" target=''_blank''  style=\"\$fontcolor;\$fontweight\">\$title</a></div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:6:\"fenlei\";s:6:\"wninfo\";s:7:\"fenlei_\";s:7:\"typefid\";N;s:6:\"cityId\";s:17:\"\$GLOBALS[city_id]\";s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:24:\"/common_title/0title.jpg\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";s:0:\"\";s:5:\"stype\";s:1:\"t\";s:2:\"yz\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:4:\"list\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:1:\"5\";s:3:\"sql\";s:132:\"(SELECT * FROM qb_fenlei_content  WHERE city_id=''\$GLOBALS[city_id]''  AND city_id=''\$GLOBALS[city_id]'' ) ORDER BY list DESC LIMIT 0,5 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"20\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1306894949','0','1','0','0','blue');");
E_D("replace into `qb_label` values('3','','0','0','azure_mainbanner','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../images/azure/ad1.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"990\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','azure');");
E_D("replace into `qb_label` values('4','','0','0','hy_indext1','Info_hy_','1','a:29:{s:13:\"tplpart_1code\";s:372:\"<div class=\"listpica\"> \r\n<div class=\"img\"><a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\"><img src=\"\$picurl\" onerror=\"this.src=''\$webdb[www_url]/images/default/nopic.jpg''\"  height=\"45\"/></a> </div>\r\n<div class=\"word\">\r\n	<div class=\"t\"><a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\">\$title</a> </div>\r\n    <div class=\"m\">{\$content}</div>\r\n</div>\r\n</div>\r\n\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:7:\"company\";s:7:\"typefid\";N;s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"40\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:29:\"/common_content/content_1.jpg\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";N;s:5:\"stype\";s:2:\"cp\";s:2:\"yz\";s:3:\"all\";s:8:\"renzheng\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:3:\"rid\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:1:\"1\";s:3:\"sql\";s:92:\"SELECT * FROM qb_hy_company  WHERE city_id=''\$GLOBALS[city_id]''  ORDER BY rid DESC LIMIT 0,1 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"20\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1314265876','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('5','','0','0','hy_indext2','Info_hy_','1','a:29:{s:13:\"tplpart_1code\";s:125:\"<div class=\"list\">·<A HREF=\"\$webdb[www_url]/home/?uid=\$uid\" target=''_blank''  style=\"\$fontcolor;\$fontweight\">\$title</a></div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:7:\"company\";s:7:\"typefid\";N;s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:24:\"/common_title/0title.jpg\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";N;s:5:\"stype\";s:1:\"t\";s:2:\"yz\";s:3:\"all\";s:8:\"renzheng\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:3:\"rid\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:1:\"4\";s:3:\"sql\";s:92:\"SELECT * FROM qb_hy_company  WHERE city_id=''\$GLOBALS[city_id]''  ORDER BY rid DESC LIMIT 1,4 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"40\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"2\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1314265831','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('6','','0','0','hy_indext3','rollpic','0','a:7:{s:13:\"tplpart_1code\";s:806:\"<script src=\"http://www_qibosoft_com/hy/images/hy/jquery.js\" type=\"text/javascript\"></script>\r\n<ul class=\"slidePic\">\r\n<!--\r\nEOT; \r\nforeach(\$listdb AS \$key=>\$rs){@extract(\$rs);\r\nprint <<<EOT\r\n-->\r\n<li>\r\n<div class=\"img\"><a href=\"\$url\" target=\"_blank\"><IMG alt=\"\$title\" src=\"\$picurl\" width=360 height=245></a></div>\r\n<div class=\"t\"><a href=\"\$url\"  target=\"_blank\">\$title</a></div>\r\n</li>\r\n<!--\r\nEOT;\r\n}\r\nprint <<<EOT\r\n-->\r\n</ul>\r\n<ul class=\"slideTxt\">\r\n<!--\r\nEOT;\r\n\$i=0;\r\nforeach(\$listdb AS \$key=>\$rs){@extract(\$rs);\$i++;\r\nif(\$i<2) {\$curclass=\"class=\\\\\"cur\\\\\"\";}\r\nelse {\$curclass=\"\";}\r\nprint <<<EOT\r\n-->\r\n<li \$curclass><IMG alt=\"\$title\" src=\"\$picurl\" width=80 height=60></li>\r\n<!--\r\nEOT;\r\n}\r\nprint <<<EOT\r\n-->\r\n</ul>\r\n<script type=\"text/javascript\" src=\"http://www_qibosoft_com/hy/images/hy/slide.js\"></script>\";s:8:\"rolltype\";s:1:\"2\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";s:6:\"picurl\";a:3:{i:1;s:58:\"http://img1.gtimg.com/gd/pics/hv1/193/187/845/54994003.jpg\";i:2;s:58:\"http://img1.gtimg.com/gd/pics/hv1/206/168/845/54989171.jpg\";i:3;s:58:\"http://img1.gtimg.com/gd/pics/hv1/176/175/844/54925901.jpg\";}s:7:\"piclink\";a:3:{i:1;s:1:\"#\";i:2;s:1:\"#\";i:3;s:1:\"#\";}s:6:\"picalt\";a:3:{i:1;s:34:\"广州买家涌至清远 一天买走700余套房\";i:2;s:33:\"深圳大运会闭幕 揭秘闭幕式精彩节目\";i:3;s:39:\"东莞公益慈善类社会组织登记松绑 登记积极\";}}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"21\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1314330162','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('7','','0','0','hy_indext4','Info_fenlei_','1','a:30:{s:13:\"tplpart_1code\";s:83:\"<div class=\"list\$i\"><span>\$i</span><a href=\"\$url\" target=\"_blank\">\$title</a></div> \";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:6:\"fenlei\";s:6:\"wninfo\";s:7:\"fenlei_\";s:7:\"typefid\";N;s:6:\"cityId\";s:17:\"\$GLOBALS[city_id]\";s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:0:\"\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";s:0:\"\";s:5:\"stype\";s:1:\"4\";s:2:\"yz\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:4:\"list\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:2:\"10\";s:3:\"sql\";s:133:\"(SELECT * FROM qb_fenlei_content  WHERE city_id=''\$GLOBALS[city_id]''  AND city_id=''\$GLOBALS[city_id]'' ) ORDER BY list DESC LIMIT 0,10 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"40\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('8','','0','0','hy_indext5','Info_hy_','1','a:29:{s:13:\"tplpart_1code\";s:302:\"<div class=\"lista\"> \r\n<div class=\"img\"><a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\"><img src=\"\$picurl\" onerror=\"this.src=''\$webdb[www_url]/images/default/nopic.jpg''\" height=\"90\" /></a></div> \r\n<div class=\"t\"> <a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\">\$title</a></div> \r\n</div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:7:\"company\";s:7:\"typefid\";N;s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:0:\"\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";N;s:5:\"stype\";s:1:\"p\";s:2:\"yz\";s:3:\"all\";s:8:\"renzheng\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:10:\"levelstime\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:2:\"10\";s:3:\"sql\";s:100:\"SELECT * FROM qb_hy_company  WHERE city_id=''\$GLOBALS[city_id]''  ORDER BY levelstime DESC LIMIT 0,10 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"20\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1314589785','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('9','','0','0','hy_indext6','Info_hy_','1','a:29:{s:13:\"tplpart_1code\";s:302:\"<div class=\"lista\"> \r\n<div class=\"img\"><a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\"><img src=\"\$picurl\" onerror=\"this.src=''\$webdb[www_url]/images/default/nopic.jpg''\" height=\"90\" /></a></div> \r\n<div class=\"t\"> <a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\">\$title</a></div> \r\n</div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:7:\"company\";s:7:\"typefid\";N;s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:0:\"\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";N;s:5:\"stype\";s:1:\"p\";s:2:\"yz\";s:3:\"all\";s:8:\"renzheng\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:3:\"rid\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:2:\"10\";s:3:\"sql\";s:93:\"SELECT * FROM qb_hy_company  WHERE city_id=''\$GLOBALS[city_id]''  ORDER BY rid DESC LIMIT 0,10 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"20\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1314339849','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('10','','0','0','hy_indext7','Info_hy_','1','a:29:{s:13:\"tplpart_1code\";s:302:\"<div class=\"lista\"> \r\n<div class=\"img\"><a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\"><img src=\"\$picurl\" onerror=\"this.src=''\$webdb[www_url]/images/default/nopic.jpg''\" height=\"90\" /></a></div> \r\n<div class=\"t\"> <a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\">\$title</a></div> \r\n</div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:7:\"company\";s:7:\"typefid\";N;s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:0:\"\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";N;s:5:\"stype\";s:1:\"p\";s:2:\"yz\";s:3:\"all\";s:8:\"renzheng\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:4:\"hits\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:2:\"10\";s:3:\"sql\";s:94:\"SELECT * FROM qb_hy_company  WHERE city_id=''\$GLOBALS[city_id]''  ORDER BY hits DESC LIMIT 0,10 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"20\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('11','','0','0','hy_indext8','Info_fenlei_','1','a:30:{s:13:\"tplpart_1code\";s:234:\"<li> \r\n<div class=\"img\"><a href=\"\$url\" target=\"_blank\"><img src=\"\$picurl\" onerror=\"this.src=''\$webdb[www_url]/images/default/nopic.jpg''\" height=\"90\" /></a></div> \r\n<div class=\"t\"> <a href=\"\$url\" target=\"_blank\">\$title</a></div> \r\n</li>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:6:\"fenlei\";s:6:\"wninfo\";s:7:\"fenlei_\";s:7:\"typefid\";N;s:6:\"cityId\";s:17:\"\$GLOBALS[city_id]\";s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:0:\"\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";s:0:\"\";s:5:\"stype\";s:1:\"p\";s:2:\"yz\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:4:\"list\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:2:\"10\";s:3:\"sql\";s:145:\"(SELECT * FROM qb_fenlei_content  WHERE ispic=1 AND city_id=''\$GLOBALS[city_id]''  AND city_id=''\$GLOBALS[city_id]'' ) ORDER BY list DESC LIMIT 0,10 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"20\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('12','','0','0','hy_indext10','Info_hy_','1','a:29:{s:13:\"tplpart_1code\";s:460:\"<div class=\"listtz\"> \r\n<div class=\"num\">\$i</div>\r\n<div class=\"img\"><a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\"><img src=\"\$picurl\" onerror=\"this.src=''\$webdb[www_url]/images/default/nopic.jpg''\" height=\"50\"/></a> </div>\r\n<div class=\"word\">\r\n<div class=\"t\"><a href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\">\$title</a> </div>\r\n<div class=\"m\">关注度:<span>\$hits</span>次</div>\r\n<div class=\"m\">点评数:<span>\$dianping</span>次</div>\r\n</div>\r\n</div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:7:\"company\";s:7:\"typefid\";N;s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:0:\"\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";N;s:5:\"stype\";s:1:\"p\";s:2:\"yz\";s:3:\"all\";s:8:\"renzheng\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:10:\"levelstime\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:1:\"5\";s:3:\"sql\";s:99:\"SELECT * FROM qb_hy_company  WHERE city_id=''\$GLOBALS[city_id]''  ORDER BY levelstime DESC LIMIT 0,5 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"30\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1314347209','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('13','','0','0','hy_indext11','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../hy/images/hy/ad1.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"190\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"21\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1314351044','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('14','','0','0','hylistt1','Info_hy_','1','a:29:{s:13:\"tplpart_1code\";s:92:\"<div class=\"list\"><A HREF=\"\$webdb[www_url]/home/?uid=\$uid\" target=''_blank'' >\$title</a></div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:7:\"company\";s:7:\"typefid\";N;s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:24:\"/common_title/0title.jpg\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";N;s:5:\"stype\";s:1:\"t\";s:2:\"yz\";s:3:\"all\";s:8:\"renzheng\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:10:\"levelstime\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:2:\"15\";s:3:\"sql\";s:100:\"SELECT * FROM qb_hy_company  WHERE city_id=''\$GLOBALS[city_id]''  ORDER BY levelstime DESC LIMIT 0,15 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"50\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','2','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('15','','0','0','hy_indext15','pic','0','a:5:{s:6:\"imgurl\";s:23:\"../hy/images/hy/ad3.gif\";s:7:\"imglink\";s:19:\"http://www.haoid.cn\";s:5:\"width\";s:3:\"815\";s:6:\"height\";s:2:\"60\";s:11:\"pic_city_id\";i:0;}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"21\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1388480731','0','3','0','0','blue');");
E_D("replace into `qb_label` values('16','','0','0','hy_indext12','code','0','<div>·<a href=\"#\" target=\"_blank\">为什么要申请金牌会员</a></div>\r\n<div>·<a href=\"#\" target=\"_blank\">注册普通会员收费吗?</a></div>\r\n<div>·<a href=\"#\" target=\"_blank\">注册后忘记登录名和密码怎么办</a></div>','a:4:{s:9:\"html_edit\";N;s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"21\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1314350804','0','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('17','','0','0','hylistt2','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../hy/images/hy/ad3.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"990\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','2','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('18','','0','0','hylistallt1','Info_hy_','1','a:29:{s:13:\"tplpart_1code\";s:92:\"<div class=\"list\"><A HREF=\"\$webdb[www_url]/home/?uid=\$uid\" target=''_blank'' >\$title</a></div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:7:\"company\";s:7:\"typefid\";N;s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:0:\"\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";N;s:5:\"stype\";s:1:\"4\";s:2:\"yz\";s:3:\"all\";s:8:\"renzheng\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:10:\"levelstime\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:2:\"15\";s:3:\"sql\";s:100:\"SELECT * FROM qb_hy_company  WHERE city_id=''\$GLOBALS[city_id]''  ORDER BY levelstime DESC LIMIT 0,15 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"40\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','4','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('19','','0','0','hylistallt2','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../hy/images/hy/ad3.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"990\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','4','3','0','0','azure_tpl');");
E_D("replace into `qb_label` values('20','','0','0','green_companyt','Info_hy_','1','a:29:{s:13:\"tplpart_1code\";s:229:\"<dl>\r\n<dt><a  href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\"><img src=\"\$picurl\" height=\"75\"/></a></dt>\r\n<dd>\r\n<div><a  href=\"\$webdb[www_url]/home/?uid=\$uid\" target=\"_blank\">\$title</a></div>\r\n<p>\$content</p>\r\n</dd>\r\n</dl>\r\n\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:7:\"company\";s:7:\"typefid\";N;s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:11:\"content_num\";s:2:\"80\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:2:\"30\";s:7:\"tplpath\";s:29:\"/common_content/content_1.jpg\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:8:\"moduleid\";N;s:5:\"stype\";s:2:\"cp\";s:2:\"yz\";s:3:\"all\";s:8:\"renzheng\";s:3:\"all\";s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:10:\"levelstime\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:1:\"6\";s:3:\"sql\";s:99:\"SELECT * FROM qb_hy_company  WHERE city_id=''\$GLOBALS[city_id]''  ORDER BY levelstime DESC LIMIT 0,6 \";s:7:\"colspan\";s:1:\"1\";s:8:\"titlenum\";s:2:\"40\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";}','a:3:{s:5:\"div_w\";s:3:\"775\";s:5:\"div_h\";s:3:\"234\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1322103539','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('21','','0','0','green_slide','rollpic','0','a:8:{s:13:\"tplpart_1code\";s:280:\"<TABLE id=\"pictable\" style=\"DISPLAY: none\">\r\n <TBODY>\r\n<!--\r\nEOT;\r\nforeach(\$listdb AS \$key=>\$rs){@extract(\$rs);\r\nprint <<<EOT\r\n-->\r\n   <tr>\r\n    <td><img src=\"\$picurl\"/></td>\r\n    <td> \$title</td>\r\n    <td>\$url</td>\r\n   </tr>\r\n<!--\r\nEOT;\r\n}\r\nprint <<<EOT\r\n-->\r\n </TBODY>\r\n</TABLE>\";s:8:\"rolltype\";s:1:\"2\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";s:6:\"picurl\";a:3:{i:1;s:21:\"../images/green/1.gif\";i:2;s:21:\"../images/green/2.jpg\";i:3;s:21:\"../images/green/3.jpg\";}s:7:\"piclink\";a:3:{i:1;s:21:\"http://www.domain.com\";i:2;s:21:\"http://www.domain.com\";i:3;s:21:\"http://www.domain.com\";}s:6:\"picalt\";a:3:{i:1;s:25:\"测试1测试1测试1测试1测试1\";i:2;s:25:\"测试1测试1测试1测试1测试1\";i:3;s:25:\"测试1测试1测试1测试1测试1\";}s:11:\"pic_city_id\";i:0;}','a:3:{s:5:\"div_w\";s:3:\"499\";s:5:\"div_h\";s:3:\"282\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1388468439','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('22','','0','0','green_listad1','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../images/green/ad1.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"165\";s:6:\"height\";s:2:\"85\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('23','','0','0','green_listad3','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../images/green/ad1.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"165\";s:6:\"height\";s:2:\"82\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"21\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1322104345','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('24','','0','0','green_listad2','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../images/green/ad2.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"165\";s:6:\"height\";s:2:\"85\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('25','','0','0','green_listad4','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../images/green/ad3.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"815\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('26','','0','0','green_listad7','pic','0','a:4:{s:6:\"imgurl\";s:27:\"../images/green/dbanner.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"990\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('27','','0','0','green_listad5','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../images/green/ad4.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"265\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('28','','0','0','green_listad6','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../images/green/ad5.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"265\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('29','','0','0','green_listad8','pic','0','a:4:{s:6:\"imgurl\";s:23:\"../images/green/ad6.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"265\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('30','','0','0','green_listwad1','code','0','<div class=\"list\"><a href=\"http://www.domain.com\">虚位以待</a></div>\r\n<div class=\"list\"><a href=\"http://www.domain.com\">虚位以待</a></div>\r\n<div class=\"list\"><a href=\"http://www.domain.com\">虚位以待</a></div>\r\n<div class=\"list\"><a href=\"http://www.domain.com\">虚位以待</a></div>\r\n<div class=\"list\"><a href=\"http://www.domain.com\">虚位以待</a></div>','a:4:{s:9:\"html_edit\";N;s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"21\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1388469015','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('31','','0','0','green_listwad2','code','0','<div class=\"list\"><a href=\"http://app.baidu.com/riliwannianli/index.html\" target=\"_blank\">万年历</a></div>\r\n<div class=\"list\"><a href=\"http://bus.mapbar.com\" target=\"_blank\">公交查询</a></div>\r\n<div class=\"list\"><a href=\"http://huoche.kuxun.cn/index.html\" target=\"_blank\">火车查询</a></div>\r\n<div class=\"list\"><a href=\"http://www.ip138.com/ips.asp\" target=\"_blank\">IP查询</a></div>\r\n<div class=\"list\"><a href=\"http://www.360.cn/\" target=\"_blank\">在线杀毒</a></div>\r\n<div class=\"list\"><a href=\"http://www.ip138.com/post/\" target=\"_blank\">邮编区号</a></div>\r\n<div class=\"list\"><a href=\"http://tvguide.ent.sina.com.cn/\" target=\"_blank\">电视预告</a></div>\r\n<div class=\"list\"><a href=\"http://banlv.baidu.com/\" target=\"_blank\">百度伴侣</a></div>\r\n<div class=\"list\"><a href=\"http://quote.eastmoney.com/zs000001.html\" target=\"_blank\">股票查询</a></div>\r\n<div class=\"list\"><a href=\"http://www.icbc.com.cn/icbc/\" target=\"_blank\">工商银行</a></div>\r\n<div class=\"list\"><a href=\"http://caipiao.hao123.com/\" target=\"_blank\">彩票查询</a></div>\r\n<div class=\"list\"><a href=\"http://weather.news.sina.com.cn/\" target=\"_blank\">天气预报</a></div>\r\n<div class=\"list\"><a href=\"http://www.ctrip.com/\" target=\"_blank\">飞机航班</a></div>\r\n<div class=\"list\"><a href=\"http://astro.lady.qq.com/\" target=\"_blank\">星座运程</a></div>\r\n<div class=\"list\"><a href=\"http://www.hao123.com/bankjt.htm\" target=\"_blank\">网上支付</a></div>\r\n<div class=\"list\"><a href=\"http://movie.hao123.com\" target=\"_blank\">免费电影</a></div>\r\n<div class=\"list\"><a href=\"http://www.ip138.com/ems/\" target=\"_blank\">快递查询</a></div>\r\n<div class=\"list\"><a href=\"http://qq.ip138.com/train/\" target=\"_blank\">列车时刻表</a></div>\r\n<div class=\"list\"><a href=\"http://www.ip138.com/sj/\" target=\"_blank\">手机查询</a></div>\r\n<div class=\"list\"><a href=\"http://qq.ip138.com/tran.htm\" target=\"_blank\">在线翻译</a></div>\r\n<div class=\"list\"><a href=\"http://qq.ip138.com/hl.asp\" target=\"_blank\">货币汇率</a></div>\r\n<div class=\"list\"><a href=\"http://jbk.39.net/\" target=\"_blank\">疾病查询</a></div>\r\n<div class=\"list\"><a href=\"http://fund.eastmoney.com/fund.html\" target=\"_blank\">基金净值</a></div>\r\n<div class=\"list\"><a href=\"http://zhougongjiemeng.1518.com/\" target=\"_blank\">周公解梦</a></div>\r\n','a:4:{s:9:\"html_edit\";N;s:5:\"div_w\";s:0:\"\";s:5:\"div_h\";s:0:\"\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('32','','0','0','green_allsortad1','pic','0','a:4:{s:6:\"imgurl\";s:27:\"../images/green/dbanner.gif\";s:7:\"imglink\";s:1:\"#\";s:5:\"width\";s:3:\"990\";s:6:\"height\";s:2:\"60\";}','a:3:{s:5:\"div_w\";s:3:\"989\";s:5:\"div_h\";s:2:\"56\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1322185801','5','1','5','0','green_tpl');");
E_D("replace into `qb_label` values('33','','0','99','green_hotline','code','0','<a href=http://www.souho.net target=_blank>搜虎精品社区</a>','a:4:{s:9:\"html_edit\";N;s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"21\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','搜虎精品社区','1379143350','0','1','0','0','green_tpl');");
E_D("replace into `qb_label` values('166','','0','0','help_index_h2','code','0','热门信息','a:4:{s:9:\"html_edit\";N;s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"21\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1345694570','0','20','0','0','green_tpl');");
E_D("replace into `qb_label` values('167','','0','0','help_index_t2','Info_help_','1','a:36:{s:13:\"tplpart_1code\";s:65:\"<div class=\"list\"><a href=\"\$url\" target=\"_blank\">\$title</a></div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:2:\"wn\";s:6:\"wninfo\";s:5:\"help_\";s:9:\"noReadMid\";s:0:\"\";s:13:\"RollStyleType\";s:0:\"\";s:7:\"fidtype\";s:1:\"0\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:3:\"100\";s:7:\"amodule\";N;s:7:\"tplpath\";s:0:\"\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:5:\"stype\";s:1:\"4\";s:2:\"yz\";s:1:\"1\";s:7:\"hidefid\";N;s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:6:\"A.hits\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:1:\"5\";s:3:\"sql\";s:82:\" SELECT A.* FROM qb_help_content A  WHERE A.yz=1   ORDER BY A.hits DESC LIMIT 0,5 \";s:4:\"sql2\";N;s:7:\"colspan\";s:1:\"1\";s:11:\"content_num\";s:2:\"80\";s:12:\"content_num2\";s:3:\"120\";s:8:\"titlenum\";s:2:\"50\";s:9:\"titlenum2\";s:2:\"40\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";s:10:\"c_rolltype\";s:1:\"0\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','0','0','20','0','0','green_tpl');");
E_D("replace into `qb_label` values('164','','0','0','help_index_h1','code','0','最新信息','a:4:{s:9:\"html_edit\";N;s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"21\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1345694565','0','20','0','0','green_tpl');");
E_D("replace into `qb_label` values('165','','0','0','help_index_t1','Info_help_','1','a:37:{s:7:\"allcity\";s:1:\"1\";s:13:\"tplpart_1code\";s:65:\"<div class=\"list\"><a href=\"\$url\" target=\"_blank\">\$title</a></div>\";s:13:\"tplpart_2code\";s:0:\"\";s:3:\"SYS\";s:2:\"wn\";s:6:\"wninfo\";s:5:\"help_\";s:9:\"noReadMid\";s:0:\"\";s:13:\"RollStyleType\";s:0:\"\";s:7:\"fidtype\";s:1:\"0\";s:8:\"rolltype\";s:10:\"scrollLeft\";s:8:\"rolltime\";s:1:\"3\";s:11:\"roll_height\";s:2:\"50\";s:5:\"width\";s:3:\"250\";s:6:\"height\";s:3:\"187\";s:7:\"newhour\";s:2:\"24\";s:7:\"hothits\";s:3:\"100\";s:7:\"amodule\";N;s:7:\"tplpath\";s:24:\"/common_title/0title.jpg\";s:6:\"DivTpl\";i:1;s:5:\"fiddb\";N;s:5:\"stype\";s:1:\"t\";s:2:\"yz\";s:1:\"1\";s:7:\"hidefid\";N;s:10:\"timeformat\";s:11:\"Y-m-d H:i:s\";s:5:\"order\";s:10:\"A.posttime\";s:3:\"asc\";s:4:\"DESC\";s:6:\"levels\";s:3:\"all\";s:7:\"rowspan\";s:1:\"8\";s:3:\"sql\";s:93:\" SELECT A.* FROM qb_help_content A  WHERE 1  AND A.yz=1   ORDER BY A.posttime DESC LIMIT 0,8 \";s:4:\"sql2\";N;s:7:\"colspan\";s:1:\"1\";s:11:\"content_num\";s:2:\"80\";s:12:\"content_num2\";s:3:\"120\";s:8:\"titlenum\";s:2:\"50\";s:9:\"titlenum2\";s:2:\"40\";s:10:\"titleflood\";s:1:\"0\";s:9:\"start_num\";s:1:\"1\";s:10:\"c_rolltype\";s:1:\"0\";}','a:3:{s:5:\"div_w\";s:2:\"50\";s:5:\"div_h\";s:2:\"30\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1345692205','0','20','0','0','green_tpl');");
E_D("replace into `qb_label` values('163','','0','0','help_index_slides','rollpic','0','a:7:{s:13:\"tplpart_1code\";s:587:\"<TABLE id=\"pictable\" style=\"DISPLAY: none\">\r\n <TBODY>\r\n<!--\r\nEOT;\r\nforeach(\$listdb AS \$key=>\$rs){@extract(\$rs);\r\nprint <<<EOT\r\n-->\r\n   <tr>\r\n    <td><img src=\"\$picurl\"/></td>\r\n    <td> \$title</td>\r\n    <td>\$url</td>\r\n   </tr>\r\n<!--\r\nEOT;\r\n}\r\nprint <<<EOT\r\n-->\r\n </TBODY>\r\n</TABLE>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"http://www_qibosoft_com/help/images/default/slide.css\">\r\n<SCRIPT LANGUAGE=\"JavaScript\" src=\"http://www_qibosoft_com/help/images/default/slide.js\"></SCRIPT>\r\n<SCRIPT LANGUAGE=\"JavaScript\" src=\"http://www_qibosoft_com/help/images/default/show_slide.js\"></SCRIPT>\";s:8:\"rolltype\";s:1:\"2\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";s:6:\"picurl\";a:5:{i:1;s:28:\"../help/images/default/1.jpg\";i:2;s:28:\"../help/images/default/2.jpg\";i:3;s:28:\"../help/images/default/3.jpg\";i:4;s:28:\"../help/images/default/4.jpg\";i:5;s:28:\"../help/images/default/5.jpg\";}s:7:\"piclink\";a:5:{i:1;s:23:\"http://www.qibosoft.com\";i:2;s:23:\"http://bbs.qibosoft.com\";i:3;s:23:\"http://www.qibosoft.com\";i:4;s:23:\"http://bbs.qibosoft.com\";i:5;s:23:\"http://www.qibosoft.com\";}s:6:\"picalt\";a:5:{i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";i:4;s:1:\"4\";i:5;s:1:\"5\";}}','a:3:{s:5:\"div_w\";s:3:\"637\";s:5:\"div_h\";s:3:\"216\";s:11:\"div_bgcolor\";s:0:\"\";}','0','0','1','admin','1345538239','0','20','0','0','green_tpl');");

require("../../inc/footer.php");
?>