<?php
error_reporting(0);
if(ereg("^([-_0-9a-zA-Z]+)$",$_GET[jobs])){
	//不读数据库
	if(is_file(dirname(__FILE__)."/../inc/job/$_GET[jobs].php")){
		include(dirname(__FILE__)."/../inc/job/$_GET[jobs].php");
	}
}elseif(ereg("^([-_0-9a-zA-Z]+)$",$_GET[job])||ereg("^([-_0-9a-zA-Z]+)$",$_POST[job])){
	//读数据库
	require(dirname(__FILE__)."/"."global.php");
	if(ereg("^([-_0-9a-zA-Z]+)$",$job)&&is_file(ROOT_PATH."inc/job/$job.php")){
		include(ROOT_PATH."inc/job/$job.php");
	}
}
?>